"""
Forest-plot style comparison across our two architectures (ViT/"transformer",
Max Conv2D/"max_2dconv"), two dataset conditions (raw-charge pixelAV / our own
post-CSA "frontend effects"), and precision variant as a sub-category within
each -- adapted from the prior team's compare-res-3sr-ONEBIG.ipynb
(upstream/main:summary-plots/), same underlying idea (one point + asymmetric
shortest-68%-interval error bar per condition, compared side by side).

Both residuals_frontend.json (generated by aggregate_frontend_results.py) and
residuals_pixelav_3sr.json (a verbatim copy of the real dataset3sr/residuals.json,
see convert_dataset3sr_residuals.py) share the exact same structure/key-naming
-- architecture keys "transformer"/"max_2dconv"/etc., variant keys
"1-noquant_20t"/"2-noquant_2t"/"3-input_dig_2t"/"4-quantized", and per-quantity
fields mean_<v>/std_<v>/up68_<v>/down68_<v>/mean_upsigma<v>/mean_downsigma<v>
for v in x, y, cotA, cotB, A (alpha, deg), B (beta, deg) -- so this script
reads both through one code path, no format translation. residuals_pixelav_3sr.json
keeps all 7 architectures and all 4 variants from the source file; ARCHS below
controls which ones actually get drawn (currently just the two we have our own
results for -- add more here to show additional pixelAV-only architectures as
pure reference).

Identity is conveyed entirely through two legends, same style as the original
notebook: a color legend for (architecture, dataset condition) pairs -- e.g.
"ViT, Frontend effects" -- and a marker-shape legend for precision variant.
The y-axis carries no text labels at all (like the original's
`set_yticks([])`); each (architecture, dataset) combo just gets its own row
slot purely for visual separation.

Note: per direct collaborator confirmation, neither of our architectures has
a genuine full-precision variant on our own dataset -- ViT's soft/trainable-ADC
stage (Stage 1) and Max Conv2D are both always operating on digitized input in
some form, so "1-noquant_20t"/"2-noquant_2t" only ever have data on the
pixelAV side; see aggregate_frontend_results.py's docstring for the full
reasoning.
"""
import os
import json
import matplotlib
matplotlib.use("Agg")
import matplotlib.pyplot as plt

here = os.path.dirname(os.path.abspath(__file__))

# which architectures to actually draw (keys match the JSON files' own naming)
ARCHS = ["transformer", "max_2dconv"]
ARCH_LABELS = {"transformer": "ViT", "max_2dconv": "Max Conv2D"}
DATASETS = ["pixelav", "frontend"]
DATASET_LABELS = {"pixelav": "pixelAV (raw charge, 3sr dataset)", "frontend": "Frontend effects"}
# blue-family for ViT, orange-family for Max Conv2D; darker/solid = frontend
# (our own realistic result), lighter = pixelAV (prior reference)
GROUP_COLORS = {
    ("transformer", "frontend"): "tab:blue",
    ("transformer", "pixelav"): "tab:cyan",
    ("max_2dconv", "frontend"): "tab:orange",
    ("max_2dconv", "pixelav"): "tab:red",
}
VARIANTS = ["1-noquant_20t", "2-noquant_2t", "3-input_dig_2t", "4-quantized"]
VARIANT_LABELS = {
    "1-noquant_20t": "Full precision, 20 frames",
    "2-noquant_2t": "Full precision, 2 frames",
    "3-input_dig_2t": "Digitized inputs",
    "4-quantized": "Quantized NN",
}
VARIANT_MARKERS = {"1-noquant_20t": "D", "2-noquant_2t": "o", "3-input_dig_2t": "s", "4-quantized": "^"}
QUANTITIES = [("x", r"$R_x$ [um]", (-15, 15)), ("y", r"$R_y$ [um]", (-8, 8)),
              ("A", r"$R_\alpha$ [deg]", (-8, 8)), ("B", r"$R_\beta$ [deg]", (-8, 8))]

# explicit row order (top to bottom): pixelAV rows first (grouped together,
# any architecture), then ViT frontend, then Max Conv2D frontend
GROUP_ORDER = [
    ("max_2dconv", "pixelav"),
    ("transformer", "pixelav"),
    ("transformer", "frontend"),
    ("max_2dconv", "frontend"),
]


def load(name):
    path = os.path.join(here, f"residuals_{name}.json")
    if not os.path.exists(path):
        print(f"({path} not found -- skipping {name} data)")
        return {}
    with open(path) as f:
        return json.load(f)


def main():
    data = {"pixelav": load("pixelav_3sr"), "frontend": load("frontend")}

    groups = [g for g in GROUP_ORDER if g[0] in ARCHS and
              any(variant in data[g[1]].get(g[0], {}) for variant in VARIANTS)]

    if not groups:
        raise SystemExit("No data found in residuals_frontend.json / residuals_pixelav_3sr.json.")

    fig, axes = plt.subplots(1, 4, figsize=(20, 0.7 * len(groups) + 2), sharey=True)

    y_positions = list(range(len(groups), 0, -1))

    for ax, (quantity, xlabel, xlim) in zip(axes, QUANTITIES):
        ax.axvline(0, color="gray", zorder=0, lw=1)
        for (arch, dataset), y0 in zip(groups, y_positions):
            color = GROUP_COLORS[(arch, dataset)]
            variants_here = data[dataset].get(arch, {})
            for i, variant in enumerate(VARIANTS):
                stats = variants_here.get(variant)
                if stats is None:
                    continue
                y = y0 + 0.3 - 0.15 * i
                mean = stats[f"mean_{quantity}"]
                up = stats[f"up68_{quantity}"]
                down = stats[f"down68_{quantity}"]
                # wide, translucent band: the model's own mean predicted
                # uncertainty (sigma output), vs. the thin bar's actual measured
                # 68%-interval spread -- shows whether predicted uncertainty is
                # well-calibrated. Optional: skipped if not present in the data.
                up_sigma = stats.get(f"mean_upsigma{quantity}")
                down_sigma = stats.get(f"mean_downsigma{quantity}")
                if up_sigma is not None and down_sigma is not None:
                    ax.errorbar(mean, y, xerr=[[down_sigma], [up_sigma]], color=color,
                                elinewidth=10, alpha=0.2, linestyle="")
                ax.errorbar(mean, y, xerr=[[down], [up]], color=color,
                            marker=VARIANT_MARKERS[variant], linestyle="", capsize=3)
        ax.set_xlabel(xlabel)
        ax.set_xlim(*xlim)
        ax.set_yticks([])
        ax.grid(True, axis="x", alpha=0.3)

    axes[0].set_ylim(0.5, len(groups) + 0.8)

    # two legends, same style as the original notebooks: colored lines -> (architecture,
    # dataset) group, marker shapes -> precision variant
    group_handles = [plt.Line2D([0], [0], color=GROUP_COLORS[g], lw=2,
                                 label=f"{ARCH_LABELS[g[0]]}, {DATASET_LABELS[g[1]]}")
                      for g in groups]
    variant_handles = [plt.Line2D([0], [0], marker=VARIANT_MARKERS[v], color="black",
                                   linestyle="", label=VARIANT_LABELS[v]) for v in VARIANTS]
    leg1 = fig.legend(handles=group_handles, loc="upper left", ncol=1,
                       bbox_to_anchor=(0.02, 1.1), frameon=False)
    fig.add_artist(leg1)
    fig.legend(handles=variant_handles, loc="upper right", ncol=1,
               bbox_to_anchor=(0.98, 1.1), frameon=False)

    fig.suptitle("Residual comparison: Different architectures and pixelAV vs frontend effects", y=1.15)
    plt.tight_layout()
    out_path = os.path.join(here, "residual_comparison.png")
    plt.savefig(out_path, dpi=120, bbox_inches="tight")
    print(f"saved to {out_path}")

    # report what's missing, for visibility
    print("\nMissing (arch, dataset, variant) combos:")
    for arch in ARCHS:
        for dataset in DATASETS:
            for variant in VARIANTS:
                if variant not in data[dataset].get(arch, {}):
                    print(f"  {arch} / {dataset} / {variant}")


if __name__ == "__main__":
    main()
