"""
Forest-plot style comparison across our two architectures (ViT, Max Conv2D),
two dataset conditions (raw-charge pixelAV / our own post-CSA "frontend
effects"), and three precision variants (full-precision-2-frames, digitized
inputs, quantized NN) -- adapted from the prior team's
compare-res-3sr-ONEBIG.ipynb (upstream/main:summary-plots/), same underlying
idea (one point + asymmetric shortest-68%-interval error bar per condition,
compared side by side).

Identity is conveyed entirely through two legends, same style as the
original notebook: a color legend for (architecture, dataset condition) pairs
-- e.g. "ViT, Frontend effects" -- and a marker-shape legend for precision
variant. The y-axis carries no text labels at all (like the original's
`set_yticks([])`); each (architecture, dataset) combo just gets its own row
slot purely for visual separation.

Note: per direct collaborator confirmation, neither of our architectures has
a genuine full-precision variant -- ViT's soft/trainable-ADC stage (Stage 1)
and Max Conv2D are both always operating on digitized input in some form, so
"full_precision_2frames" only ever has data on the pixelAV side (if at all);
see aggregate_frontend_results.py's docstring for the full reasoning.

Reads residuals_frontend.json (always present, generated by
aggregate_frontend_results.py) and residuals_pixelav.json (optional -- supply
your own, see residuals_pixelav.template.json for the expected schema; the
plot just skips any (arch, dataset, variant) combo missing from either file,
no fabricated placeholders).
"""
import os
import json
import matplotlib
matplotlib.use("Agg")
import matplotlib.pyplot as plt

here = os.path.dirname(os.path.abspath(__file__))

ARCHS = ["vit", "max_conv2d"]
ARCH_LABELS = {"vit": "ViT", "max_conv2d": "Max Conv2D"}
DATASETS = ["pixelav", "frontend"]
DATASET_LABELS = {"pixelav": "pixelAV (raw charge)", "frontend": "Frontend effects"}
# blue-family for ViT, orange-family for Max Conv2D; darker/solid = frontend
# (our own realistic result), lighter = pixelAV (prior reference)
GROUP_COLORS = {
    ("vit", "frontend"): "tab:blue",
    ("vit", "pixelav"): "tab:cyan",
    ("max_conv2d", "frontend"): "tab:orange",
    ("max_conv2d", "pixelav"): "tab:red",
}
VARIANTS = ["full_precision_2frames", "digitized_inputs", "quantized_nn"]
VARIANT_LABELS = {
    "full_precision_2frames": "Full precision, 2 frames",
    "digitized_inputs": "Digitized inputs",
    "quantized_nn": "Quantized NN",
}
VARIANT_MARKERS = {"full_precision_2frames": "o", "digitized_inputs": "s", "quantized_nn": "^"}
QUANTITIES = [("x", r"$R_x$ [um]", (-15, 15)), ("y", r"$R_y$ [um]", (-8, 8)),
              ("A", r"$R_\alpha$ [deg]", (-8, 8)), ("B", r"$R_\beta$ [deg]", (-8, 8))]


def load(name):
    path = os.path.join(here, f"residuals_{name}.json")
    if not os.path.exists(path):
        print(f"({path} not found -- skipping {name} data)")
        return {}
    with open(path) as f:
        return json.load(f)


def main():
    data = {"pixelav": load("pixelav"), "frontend": load("frontend")}

    # one row slot per (arch, dataset) group that has at least one variant present
    groups = []
    for arch in ARCHS:
        for dataset in DATASETS:
            if any(variant in data[dataset].get(arch, {}) for variant in VARIANTS):
                groups.append((arch, dataset))

    if not groups:
        raise SystemExit("No data found in residuals_frontend.json / residuals_pixelav.json.")

    fig, axes = plt.subplots(1, 4, figsize=(20, 0.7 * len(groups) + 2), sharey=True)

    y_positions = list(range(len(groups), 0, -1))

    for ax, (quantity, xlabel, xlim) in zip(axes, QUANTITIES):
        ax.axvline(0, color="gray", zorder=0, lw=1)
        for (arch, dataset), y0 in zip(groups, y_positions):
            color = GROUP_COLORS[(arch, dataset)]
            variants_here = data[dataset].get(arch, {})
            for i, variant in enumerate(VARIANTS):
                stats = variants_here.get(variant)
                if stats is None:
                    continue
                y = y0 + 0.25 - 0.2 * i
                mean = stats[f"mean_{quantity}"]
                up = stats[f"up68_{quantity}"]
                down = stats[f"down68_{quantity}"]
                # wide, translucent band: the model's own mean predicted
                # uncertainty (sigma output), vs. the thin bar's actual measured
                # 68%-interval spread -- shows whether predicted uncertainty is
                # well-calibrated. Optional: skipped if not present in the data.
                up_sigma = stats.get(f"mean_upsigma_{quantity}")
                down_sigma = stats.get(f"mean_downsigma_{quantity}")
                if up_sigma is not None and down_sigma is not None:
                    ax.errorbar(mean, y, xerr=[[down_sigma], [up_sigma]], color=color,
                                elinewidth=10, alpha=0.2, linestyle="")
                ax.errorbar(mean, y, xerr=[[down], [up]], color=color,
                            marker=VARIANT_MARKERS[variant], linestyle="", capsize=3)
        ax.set_xlabel(xlabel)
        ax.set_xlim(*xlim)
        ax.set_yticks([])
        ax.grid(True, axis="x", alpha=0.3)

    axes[0].set_ylim(0.5, len(groups) + 0.8)

    # two legends, same style as the original notebooks: colored lines -> (architecture,
    # dataset) group, marker shapes -> precision variant
    group_handles = [plt.Line2D([0], [0], color=GROUP_COLORS[g], lw=2,
                                 label=f"{ARCH_LABELS[g[0]]}, {DATASET_LABELS[g[1]]}")
                      for g in groups]
    variant_handles = [plt.Line2D([0], [0], marker=VARIANT_MARKERS[v], color="black",
                                   linestyle="", label=VARIANT_LABELS[v]) for v in VARIANTS]
    leg1 = fig.legend(handles=group_handles, loc="upper left", ncol=1,
                       bbox_to_anchor=(0.02, 1.1), frameon=False)
    fig.add_artist(leg1)
    fig.legend(handles=variant_handles, loc="upper right", ncol=1,
               bbox_to_anchor=(0.98, 1.1), frameon=False)

    fig.suptitle("Precision comparison: ViT vs Max Conv2D, pixelAV vs frontend effects", y=1.15)
    plt.tight_layout()
    out_path = os.path.join(here, "precision_comparison.png")
    plt.savefig(out_path, dpi=120, bbox_inches="tight")
    print(f"saved to {out_path}")

    # report what's missing, for visibility
    print("\nMissing (arch, dataset, variant) combos:")
    for arch in ARCHS:
        for dataset in DATASETS:
            for variant in VARIANTS:
                if variant not in data[dataset].get(arch, {}):
                    print(f"  {arch} / {dataset} / {variant}")


if __name__ == "__main__":
    main()
